# Web-Only Deployment Workflow for Vikunja
name: Deploy to Heroku

on:
  push:
    branches:
      - 'apm-essense-groove-heroku'

env:
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      - name: Set the App Stack to Container
        run: heroku stack:set container --app ${{ env.HEROKU_APP_NAME }}
        
      # We now only build and push the WEB image
      - name: Build and push the WEB image
        run: heroku container:push web --arg "VIKUNJA_BUILD_TARGET=web" --app ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku environment variables
        run: |
          heroku config:set VIKUNJA_DATABASE_TYPE=postgres --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set VIKUNJA_SERVICE_FRONTENDURL=https://${{ env.HEROKU_APP_NAME }}.herokuapp.com --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set VIKUNJA_API_URL=https://${{ env.HEROKU_APP_NAME }}.herokuapp.com/api/v1 --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set VIKUNJA_SERVICE_JWTSECRET=${{ secrets.VIKUNJA_SERVICE_JWTSECRET }} --app ${{ env.HEROKU_APP_NAME }}

      # We now only release the 'web' container
      - name: Release new image
        run: heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
