# GitHub Action to deploy Vikunja to Heroku using Docker
name: Deploy to Heroku

# Run this workflow every time a change is pushed to the 'main' branch
on:
  push:
    branches:
      - 'apm-essense-groove-heroku' # Or 'master', depending on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Use the modern, maintained Heroku Docker deployment action
      - name: Build, Push and Release to Heroku
        uses: gonuit/heroku-docker-deploy@v2 # CORRECTED LINE
        with:
          # Use the secrets you have already configured in your repository settings
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          
          # Tell the action where to find the Dockerfile
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          
          # Pass all the necessary environment variables directly to Heroku
          heroku_config_vars: |
            VIKUNJA_DATABASE_TYPE: postgres
            VIKUNJA_SERVICE_FRONTENDURL: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
            VIKUNJA_API_URL: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api/v1
            VIKUNJA_SERVICE_JWTSECRET: ${{ secrets.VIKUNJA_SERVICE_JWTSECRET }}
