# The Final-Final Heroku Deployment Workflow
name: Deploy to Heroku via Git

on:
  push:
    branches:
      - 'apm-essense-groove-heroku'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Create .netrc file for Heroku Git authentication
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF

      - name: Add Heroku remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      # THIS IS THE CRITICAL NEW STEP
      - name: Set API dyno to web type
        run: heroku ps:type api=web -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Push to Heroku to trigger build
        run: git push heroku HEAD:main --force
