# New workflow to deploy using Heroku's native build system
name: Deploy to Heroku

on:
  push:
    branches:
      - 'apm-essense-groove-heroku'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code from your repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Use the official Heroku Deploy action
      # This action will push your source code to Heroku. Heroku will then
      # find the heroku.yml file and take over the build and release process.
      - name: Deploy to Heroku
        uses: heroku/deploy@v7
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
